# This is a basic workflow to help you get started with Actions

name: Build Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    #  - name: Download dependencies
    #    run: |
    #      sudo apt-get install build-essential
    #      sudo apt-get install scons pkg-config
    #      sudo apt-get install libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev
    #      sudo apt-get install libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      
      - name: Build Godot Editor
        run: |
          cd ${GITHUB_WORKSPACE}/godot
          ls -all







